# Generated by Django 4.1 on 2023-07-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Título')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media')),
                ('texto', models.TextField(blank=True, null=True)),
                ('ordenamiento', models.IntegerField(verbose_name='Nº de órden')),
            ],
            options={
                'verbose_name': 'Dato de página de inicio',
                'verbose_name_plural': 'Datos de página de inicio',
                'ordering': ['-ordenamiento'],
            },
        ),
    ]
