# Generated by Django 4.1 on 2023-07-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inicio',
            name='titulo',
        ),
    ]
