# Generated by Django 4.1 on 2023-07-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_remove_inicio_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inicio',
            name='title',
            field=models.CharField(default='Modifica el título', max_length=150, verbose_name='Título'),
        ),
    ]
