# Generated by Django 4.1 on 2023-07-11 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_alter_inicio_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inicio',
            options={'ordering': ['ordenamiento'], 'verbose_name': 'Dato de página de inicio', 'verbose_name_plural': 'Datos de página de inicio'},
        ),
    ]
