# Generated by Django 4.1 on 2023-07-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('subtitulo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Sub título')),
                ('autor', models.CharField(blank=True, max_length=150, null=True, verbose_name='Sub título')),
                ('contenido', models.TextField(blank=True, null=True)),
                ('imagen_1', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('imagen_2', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('imagen_3', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('imagen_4', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('ordenamiento', models.IntegerField()),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['ordenamiento'],
            },
        ),
    ]
