# Generated by Django 4.1 on 2023-07-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_alter_noticia_autor_alter_noticia_contenido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='fecha_modificacion',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fecha_publicacion',
            field=models.DateField(),
        ),
    ]
