# Generated by Django 4.1 on 2023-07-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_remove_noticia_contenido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
    ]
