# Generated by Django 4.1 on 2023-07-12 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['ordenamiento']},
        ),
    ]
